---
# - name: 'Download wordpress'
#   get_url:
#     url: https://wordpress.org/latest.tar.gz
#     dest: /tmp/wordpress.tar.gz

- name: 'Extract wordpress'
  ansible.builtin.unarchive:
    src: '/tmp/wordpress.tar.gz' 
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Copy file wp-config-sample for wp-config'
  ansible.builtin.copy:
    src: "{{ var_wp_dir_installation }}/wp-config-sample.php"
    dest: "{{ var_wp_dir_installation }}/wp-config.php"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0644

- name: 'Replace configuration database data in wp-config.php'
  ansible.builtin.replace:
    path: "{{ var_wp_dir_installation }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{item.value}}"
  with_items:
    - {regex: 'database_name_here', value: "{{ var_wp_name_db }}"}
    - {regex: 'username_here', value: "{{ var_wp_name_user }}"}
    - {regex: 'password_here', value: "{{ var_wp_password_db }}"}
    - {regex: 'localhost', value: "{{ var_wp_host_ip }}"} #<- x.x.x.x será o ip da maquina que tem o banco de dados 

- name: 'Configuration apache2 from serve wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  notify:
    - Restart apache2

#- name: 'Configuration apache2 from serve wordpress'
#  copy:
#    src: '/home/server/alura/files/conf/apache2/000-default.conf'
#    dest: '/etc/apache2/sites-available/000-default.conf'
#  notify:
#    - Restart apache2