---
- hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:
          - name: 'Intall packages'
            apt:
                    name: ['php7.3', 'apache2', 'libapache2-mod-php7.3', 'php7.3-gd', 'php-ssh2', 'python-mysqldb', 'php7.3-mysql', 'php-dev', 'libmcrypt-dev','php-pear']
                    state: latest
          